### ISSUE TITLE
imports incorrect for github repo in large amount of chapter folders

### ISSUE THREAD

**Issue by zjdaniels1985** [PacktPublishing/Hands-On-Systems-Programming-with-Go#2]
The import sections for various .go files in the chapters have the wrong url for the github.com/PacktPublishing/Hands-On-System-Programming-with-Go/"ch*/...   should be updated to github.com/PacktPublishing/Hands-On-System-Programming-with-Go/**Chapter***..

**Comment by klaidliadon** [comment]
Fixed in https://github.com/PacktPublishing/Hands-On-System-Programming-with-Go/commit/831ba377ca0c3182a81e2a590bb9a4ee682caf8a
